import { useEffect, useState } from 'react';
import api, { apiError } from '../api/client.js';
import { useAuth } from '../auth/AuthContext.jsx';
import Notice from '../components/Notice.jsx';

export default function InventoryPage() {
  const { user } = useAuth(); const [rows, setRows] = useState([]); const [notice, setNotice] = useState(); const [loading, setLoading] = useState(true); const [receipt, setReceipt] = useState({ productId: '', quantity: '', note: '' }); const [showReceipt, setShowReceipt] = useState(false);
  async function load() { setLoading(true); try { const { data } = await api.get('/inventory'); setRows(data.data); } catch (err) { setNotice({ type: 'error', message: apiError(err) }); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  async function receive(event) { event.preventDefault(); try { await api.post('/inventory/receipts', receipt); setReceipt({ productId: '', quantity: '', note: '' }); setShowReceipt(false); setNotice({ message: 'Stock receipt posted to the movement ledger.' }); load(); } catch (err) { setNotice({ type: 'error', message: apiError(err) }); } }
  return <><header className="page-header"><div><p className="eyebrow">Stock visibility</p><h1>Inventory availability</h1><p>Available is always physical stock minus stock reserved by confirmed orders.</p></div>{user.role === 'ADMIN' && <button className="primary-button" onClick={() => setShowReceipt(!showReceipt)}>{showReceipt ? 'Close form' : '+ Receive stock'}</button>}</header><Notice notice={notice} />
    {showReceipt && <section className="form-card compact"><h2>Receive stock</h2><form className="form-grid two-columns" onSubmit={receive}><label>Product<select value={receipt.productId} onChange={(e) => setReceipt({ ...receipt, productId: e.target.value })} required><option value="">Select product</option>{rows.map((row) => <option value={row.productId} key={row.id}>{row.product.productCode} — {row.product.name}</option>)}</select></label><label>Quantity<input type="number" min="1" value={receipt.quantity} onChange={(e) => setReceipt({ ...receipt, quantity: e.target.value })} required /></label><label className="full-span">Internal note (optional)<input value={receipt.note} onChange={(e) => setReceipt({ ...receipt, note: e.target.value })} /></label><div className="form-actions"><button className="primary-button">Post receipt</button><button type="button" className="secondary-button" onClick={() => setShowReceipt(false)}>Cancel</button></div></form></section>}
    <section className="table-card"><div className="table-title"><h2>Live stock positions</h2><span>Read-only availability for sales</span></div>{loading ? <p className="empty-state">Loading inventory…</p> : <div className="table-scroll"><table><thead><tr><th>Product</th><th>Category</th><th>Physical</th><th>Reserved</th><th>Available</th><th>Unit</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><strong>{row.product.productCode}</strong><small>{row.product.name}</small></td><td>{row.product.category}</td><td>{row.physicalQuantity}</td><td>{row.reservedQuantity}</td><td><strong className={row.availableQuantity === 0 ? 'stock-low' : 'stock-ok'}>{row.availableQuantity}</strong></td><td>{row.product.unit}</td></tr>)}</tbody></table></div>}</section></>;
}

